[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
clipboard = "0.5.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tabled = { version = "0.16.0", features = ["derive"] }
trigram = "0.4.4"
